# Generated by Django 4.1.7 on 2023-03-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_quality_orderitem_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ShippingPrice',
            new_name='shippingPrice',
        ),
    ]
